[versions]
kotlin = "2.2.21"
kotlinForGradlePlugins = "1.9.0"
nativebuilds = "0.9.0"
symengine = "0.14.0.1"

[libraries]
nativebuilds-symengine-headers = { module = "com.ensody.nativebuilds:symengine-headers", version.ref = "symengine" }
nativebuilds-symengine-libsymengine = { module = "com.ensody.nativebuilds:symengine-libsymengine", version.ref = "symengine" }

desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.5" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-test-main =  { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit =  { module = "org.jetbrains.kotlin:kotlin-test-junit" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version = "1.8.0" }

[plugins]
nativebuilds = { id = "com.ensody.nativebuilds", version.ref = "nativebuilds" }
